<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>MAR.Productivy.Analytics.Agent</AssemblyName>
    <Product>MAR Productivy Analytics</Product>
    <Description>Agente de analítica de actividad para Windows 10 y 11</Description>
    <ApplicationIcon>mar.ico</ApplicationIcon>
    <StartupObject></StartupObject>
  </PropertyGroup>
</Project>
